### ISSUE TITLE
Content within HTML <CENTER> appears smaller

### ISSUE THREAD

**Issue by pascalandy** [Rohitkrops/paper#10]
I don't think this is normal.

![screen shot 2018-08-28 at 9 27 47 am](https://user-images.githubusercontent.com/6694151/44725997-b605ec00-aaa4-11e8-9667-5910ae84df75.jpg)

![screen shot 2018-08-28 at 9 27 16 am](https://user-images.githubusercontent.com/6694151/44725998-b605ec00-aaa4-11e8-9517-95bc1d03c703.jpg)

**Comment by Rohitkrops** [comment]
Fixed
