### ISSUE TITLE
Title issue

### ISSUE THREAD

**Issue by pascalandy** [Rohitkrops/paper#2]
## This is OK
https://play-with-ghost.com/live-demo-paper-for-barbershops/book-your-next-appointment/

![screen shot 2018-08-28 at 8 33 43 am](https://user-images.githubusercontent.com/6694151/44723126-2446b080-aa9d-11e8-8f6d-46282aba376f.jpg)

## This is NOT
https://play-with-ghost.com/live-demo-paper-for-barbershops/style-guide/

![screen shot 2018-08-28 at 8 35 00 am](https://user-images.githubusercontent.com/6694151/44723172-48a28d00-aa9d-11e8-9a4a-4aeb40135569.jpg)

I don't understand why as Both are 'posts'

**Comment by Rohitkrops** [comment]
@pascalandy  This issue is now fixed. I will email you soon.
