### ISSUE TITLE
horizontal bar needs more space

### ISSUE THREAD

**Issue by pascalandy** [Rohitkrops/paper#6]
Specially on the top.

![screen shot 2018-08-28 at 9 00 03 am](https://user-images.githubusercontent.com/6694151/44724479-cf0c9e00-aaa0-11e8-8e8d-7fa2e437b2b2.jpg)

**Comment by Rohitkrops** [comment]
Applied the fix. Here is how it looks now. 
![screen shot 2018-08-30 at 9 13 43 pm](https://user-images.githubusercontent.com/20735862/44863075-c632ec80-ac99-11e8-86ac-d97526a72da8.png)
