### ISSUE TITLE
H1 on smartphone

### ISSUE THREAD

**Issue by pascalandy** [Rohitkrops/paper#7]
This screenshot is from my iphone 7

![2018-08-28_09h03](https://user-images.githubusercontent.com/6694151/44724671-6245d380-aaa1-11e8-85f3-553a332fc6de.jpg)

1) I feel the H1 is too big and that there is too much space between the lines. 
2) Left alignment is not clean with the logo the author's picture and the paragraph.

Cheers!

**Comment by Rohitkrops** [comment]
Done.

**Comment by pascalandy** [comment]
I see all your comments :) 
Feel free to close them. I'll wait for you official go to re-test everything. Cheers!
