### ISSUE TITLE
bulletpoints

### ISSUE THREAD

**Issue by pascalandy** [Rohitkrops/paper#8]
I feel the vertical spacing is too big. It should be a bit tighter than the paragraph spacing.

![screen shot 2018-08-28 at 9 07 31 am](https://user-images.githubusercontent.com/6694151/44724862-f152eb80-aaa1-11e8-8b86-7f05d799d811.jpg)

Cheers!

**Comment by Rohitkrops** [comment]
I think these are okay especially if the point spans more than a single line. Still I can reduce a few pixels

**Comment by pascalandy** [comment]
I agree :)
