### ISSUE TITLE
SHARE THIS ARTICLE / not uniform

### ISSUE THREAD

**Issue by pascalandy** [Rohitkrops/paper#9]
## IS GOOD

![screen shot 2018-08-28 at 9 09 59 am](https://user-images.githubusercontent.com/6694151/44724999-455dd000-aaa2-11e8-8702-2f1c8eaa42c9.jpg)

## IS NOT GOOD

![screen shot 2018-08-28 at 9 09 39 am](https://user-images.githubusercontent.com/6694151/44724993-4262df80-aaa2-11e8-9179-a05fb2b404fe.jpg)

**Comment by Rohitkrops** [comment]
I am aware of it and it is not an issue. The standard post template shows tags on the left and mini share options on the right. 
![screen shot 2018-08-30 at 9 37 10 pm](https://user-images.githubusercontent.com/20735862/44864416-398a2d80-ac9d-11e8-9f30-1e0dd7aab95c.png)


Try adding a tag to your article. 
cheers 😍

I am too glad today. Your observation and reporting techniques are far better than others. keep it up.

**Comment by pascalandy** [comment]
But the label 'Share this article' disappeared. This is why it feels weird.
